### ISSUE TITLE
Issue with wait for healthy 

### ISSUE THREAD

**Issue by gr4per** [OpusCapitaBusinessNetwork/api-registrator#6]
api registrator is pushing some services over and over again flooding the logs
![image](https://cloud.githubusercontent.com/assets/22681804/24830734/f78255b8-1c8b-11e7-9eb1-4d5f6cdc83d9.png)

This in spite of logstash-gelf and elastic-TCP being healthy
![image](https://cloud.githubusercontent.com/assets/22681804/24830736/153289de-1c8c-11e7-8312-bdc5c8ae797a.png)

**Comment by sureshvarman-cronj** [comment]
Flooding logs issue is fixed, now have retry attempts and removed service infrastructure services from registering.

ToDo
Deregister the service - have to add watch for service health
Will create a separate card for this
